---
title: "db_exec"
author: "Cob Staines"
format: html
editor: visual
---

## Libraries

```{r}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, dbplyr, here, RPostgres, DBI)
```

## DB Connection

```{r}
# can we run this in a withr statement, instead of leaving the connection hanging?

tryCatch({
    print("Connecting to Database…")
    connection <- dbConnect(drv = dbDriver("Postgres"),
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"),
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_master_user"),
                 password = Sys.getenv("aws_master_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

# dbExecute(connection, "set search_path to survey_data")
# dbDisconnect(connection)
```

# Exectute:

```{r}

log_exec = "ALTER DATABASE ribbitr SET log_statement = mod"
timestamp_exec = "ALTER DATABASE ribbitr SET track_commit_timestamp = on"

dbExecute(connection, log_exec)
dbExecute(connection, timestamp_exec)
```

