---
title: "db_push"
format: html
editor: source
---

## Load Packages

```{r}

if(!require(librarian)){
  install.packages(librarian)
  library(librarian)
}

shelf(tidyverse, here, DBI, RPostgres, RIBBiTR-BII/ribbitrrr)

```

## connect to DB
```{r}

dbcon = hopToDB()

```

## compare... what is missing?
```{r}
db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
qpcr_bd_results <- read_csv(here("final_qpcr", "merged_qpcr.csv"))


remaining = db_bd %>%
  rename(bd_swab_id = sample_name_bd) %>%
  collect() %>%
  anti_join(qpcr_bd_results, by = "bd_swab_id")

write_csv(remaining, here("final_qpcr", "qpcr_backup_unaccounted.csv"))

```

## read all_qpcr table
```{r}

qpcr_bd_results <- read_csv(here("final_qpcr", "merged_qpcr_w_plate.csv"))

remaining <- read_csv(here("final_qpcr", "qpcr_backup_unaccounted.csv"))

qpcr_bd_results = bind_rows(qpcr_bd_results,
                            remaining) %>%
  rename(sample_name_bd = bd_swab_id)

compare_bd = compare_df_cols(db_bd %>%
                               filter(FALSE) %>%
                               collect(), qpcr_bd_results)

```



## Write table to DB
```{r}

dbWriteTable(dbcon, Id("survey_data", "bd_qpcr_results"), qpcr_bd_results, overwrite = TRUE)

```
