---
title: "amm_sn_sites_counts"
format: html
---

```{r}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, dbplyr, here, RPostgres, DBI, RIBBiTR-BII/ribbitrrr)

# connect to database
dbcon = hopToDB("ribbitr")

# table pointers

db_sample = tbl(dbcon, Id("survey_data", "sample"))
db_capture = tbl(dbcon, Id("survey_data", "capture"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))
```

# data
```{r}
# import travel times excell 
ddir = Sys.getenv("data_dir")  # data directory
# Keeping .csv files in a central directory. Naming convention uses download date to distinguish batches.
wddir = here(ddir, "sierra") # working data directory

sierra_travel_times = rio::import(here(wddir, "SN_AMP_sampleTransportCovariates.xlsx")) %>%
  mutate(site = as.character(site))

site_status = read_csv(here(wddir, "sn_2024_pop_status_251111.csv")) %>%
  mutate(site = as.character(site))

```

# query
```{r}
data_samps = db_sample %>%
  pivot_wider(id_cols = capture_id,
              names_from = sample_type,
              values_from = sample_name) %>%
  left_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(region == "california",
         !is.na(amp) | !is.na(mucosome) | !is.na(microbiome),
         !is.na(taxon_capture),
         taxon_capture %in% c("rana_muscosa", "rana_sierrae"),
         life_stage %in% c("adult", "subadult")) %>%
  select(capture_id,
         taxon_capture,
         life_stage,
         cmr_id,
         marked,
         amp,
         mucosome,
         microbiome,
         bd,
         time_of_capture,
         date,
         site,
         site_latitude,
         site_longitude,
         site_elevation_m,
         geographic_area,
         project_id) %>%
  collect() %>%
  arrange(date,
          bd) %>%
  left_join(sierra_travel_times %>%
              select(site,
                     est_transport_time), by = "site") %>%
  left_join(site_status, by = "site") %>%
  mutate(population = ifelse(is.na(population), site, population))

data_samps_micro_plus = data_samps %>%
  filter(!is.na(microbiome),
         !is.na(amp) | !is.na(mucosome))

write_csv(data_samps, here("staging", paste0("skin_def_sn_captured_individuals_amp_or_micro_or_muc_", today(), ".csv")))

write_csv(data_samps_micro_plus, here("staging", paste0("skin_def_sn_captured_individuals_micro+amp_or_micro+muc_", today(), ".csv")))

data_proj = data_samps %>%
  group_by(project_id) %>%
  count()

data_proj_spec = data_samps %>%
  group_by(project_id, taxon_capture) %>%
  count()

data_life_stage_proj = data_samps %>%
  group_by(life_stage, project_id) %>%
  count()

data_species = data_samps %>%
  group_by(taxon_capture) %>%
  count()

data_sites = data_samps %>%
  mutate(year = year(date)) %>%
  group_by(population) %>%
  mutate(est_transport_time = first(na.omit(est_transport_time))) %>%
  ungroup() %>%
  group_by(site,
           site_name_alt,
           population,
           site_bd_status,
           site_interventions,
           ribbitr_core,
           site_latitude,
           site_longitude,
           site_elevation_m,
           geographic_area,
           est_transport_time) %>%
  summarise(years = paste(sort(unique(year)), collapse = ", "),
            amp_samples = sum(!is.na(amp)),
            microbiome_samples = sum(!is.na(microbiome)),
            mucosome_samples = sum(!is.na(mucosome)),
            `micro+amp_or_micro+muc` = sum(!is.na(microbiome) & (!is.na(amp) | !is.na(mucosome))),
            any_samples = sum(!is.na(amp) | !is.na(microbiome) | !is.na(mucosome)),
            all_samples = sum(!is.na(amp) & !is.na(microbiome) & !is.na(mucosome)),
            .groups = "drop") %>%
  arrange(site)

write_csv(data_sites, here("staging", paste0("skin_def_sn_site_summary_", today(), ".csv")))


data_summary = data_samps %>%
  mutate(year = year(date)) %>%
  left_join(site_status, by = "site") %>%
  filter(taxon_capture %in% c("rana_muscosa", "rana_sierrae"),
         life_stage %in% c("adult", "subadult")) %>%
  summarise(years = paste(sort(unique(year)), collapse = ","),
            amp_samples = sum(!is.na(amp)),
            microbiome_samples = sum(!is.na(microbiome)),
            mucosome_samples = sum(!is.na(mucosome)),
            any_samples = sum(!is.na(amp) | !is.na(microbiome) | !is.na(mucosome)),
            all_samples = sum(!is.na(amp) & !is.na(microbiome) & !is.na(mucosome)))

```

# 70397 survey hx
```{r}
s_70397 = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site == "70397") %>%
  mutate(year = year(date)) %>%
  collect()


c_70397_2023 = db_capture %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(survey_id == "00f86c2a-035b-4898-93ab-c672c059d6ea") %>%
  collect()

s_70397_2023 = db_sample %>%
  pivot_wider(id_cols = capture_id,
              names_from = sample_type,
              values_from = sample_name) %>%
  left_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(survey_id == "00f86c2a-035b-4898-93ab-c672c059d6ea") %>%
  collect()

```

# pull and compare data
```{r}
data_old = read_csv(here("staging", "amm_sn_captured_individuals_2025-04-10.csv"))
data_new = read_csv(here("staging", "amm_sn_captured_individuals_2025-04-16.csv"))

site_old = read_csv(here("staging", "amm_sn_site_summary_2025-04-10.csv"))
site_new = read_csv(here("staging", "amm_sn_site_summary_2025-04-16.csv"))


kuna = data_samps %>%
  filter(site == "70459")

```