---
title: "database query"
format: html
editor: source
---

# setup
```{r}
# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, dbplyr, RPostgres, DBI, RIBBiTR-BII/ribbitrrr, here)

# connect to database
dbcon = hopToDB("ribbitr")

# load column metadata for survey_data (data exploration). Use to see what columns exist.
mdc = tbl(dbcon, Id("public", "all_columns")) %>%
  filter(table_schema == "survey_data") %>%
  collect()

# pointers for tables of interest
db_bdqpcr = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
db_sample = tbl(dbcon, Id("survey_data", "sample"))
db_capture = tbl(dbcon, Id("survey_data", "capture"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))
db_taxa = tbl(dbcon, Id("survey_data", "taxonomy"))

```

# build query
```{r}
# inner join capture and bd samples
# left join supporting tables
q_bsal = db_bdqpcr %>%
  inner_join(db_sample, by = "sample_id") %>%
  inner_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  left_join(db_taxa, by = c("taxon_capture" = "taxon_id")) %>%
  filter(!is.na(bsal_detected)) %>%
  select(result_id,
         sample_id,
         sample_name_bd,
         bsal_detected,
         capture_id,
         taxon_capture,
         itis_rank,
         date,
         site,
         region,
         country)
  
d_bsal = q_bsal %>%
  collect() %>%
  arrange(date,
          site)

d_bsal_positive = d_bsal %>%
  filter(bsal_detected)

species_stats = d_bsal %>%
  filter(itis_rank == "species") %>%
  group_by(taxon_capture) %>%
  summarize(n = n()) %>%
  filter(n >= 20) %>%
  arrange(taxon_capture)

bsal_stats = d_bsal %>%
  filter(taxon_capture %in% species_stats$taxon_capture) %>%
  group_by(taxon_capture, site, region, country) %>%
  summarize(n = n(),
            .groups = "drop") %>%
  arrange(country, region, site, desc(n))

vals = seq(1, 40, 1)

cum_site_spec = expand_grid(count = vals, species = species_stats$taxon_capture) %>%
  left_join(bsal_stats %>% 
              count(taxon_capture, n, name = "freq"), 
            by = c("species" = "taxon_capture")) %>%
  group_by(species, count) %>%
  summarise(cumcount = sum(freq[n >= count], na.rm = TRUE), .groups = "drop")

ggplot(cum_site_spec, aes(x = count, y = cumcount)) +
  geom_line() +
  facet_wrap("species")
  
# # fetch column metadata
# col_md = get_query_metadata(dbcon, q_bsal)
# 
# # write
# write_csv(d_bd_capture, here("staging", paste0("boraceia_bd_capture_query_", today(), ".csv")))
# write_csv(col_md, here("staging", paste0("boraceia_bd_capture_query_", today(), "_metadata.csv")))

```