---
title: "playground"
format: html
---

```{r}
librarian::shelf(tidyverse, dbplyr, here, janitor, lubridate, RPostgres, stringr, DBI, parsedate, uuid, hms, RIBBiTR-BII/ribbitrrr)
# librarian::shelf(RIBBiTR-BII/ribbitrrr, update_all = TRUE)

## Connect to DB
dbcon <- hopToDB("ribbitr")

# table pointers
# pull relevant chain tables from DB
db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
db_sample = tbl(dbcon, Id("survey_data", "sample"))

db_aural = tbl(dbcon, Id("survey_data", "aural"))
db_capture = tbl(dbcon, Id("survey_data", "capture"))
db_edna = tbl(dbcon, Id("survey_data", "edna"))
db_env = tbl(dbcon, Id("survey_data", "environmental"))
db_ves = tbl(dbcon, Id("survey_data", "ves"))

db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

db_cmr = tbl(dbcon, Id("survey_data", "cmr"))
db_taxa = tbl(dbcon, Id("survey_data", "taxonomy"))

db_lab = tbl(dbcon, Id("survey_data", "lab"))

```

# determine unique values
```{r}
data_bd = db_bd %>%
  collect()

stt = sort(unique(data_bd$standard_target_type))

pp = data_bd %>%
  filter(standard_target_type == "ITS1")

```

# all km surveys
```{r}
data_km = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(detection_type,
         detection_subtype,
         description,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    project_id == "ribbitr_pep_km",
    detection_type != "environmental"
    ) %>%
  arrange(date,
          detection_type) %>%
  collect()

poof = km_surveys %>%
  anti_join(data_km, by = c("visit_date" = "date", "survey_description" = "description"))
  

data_km = db_capture %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(capture_id,
         taxon_capture,
         detection_type,
         detection_subtype,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    project_id == "ribbitr_pep_km",
    ) %>%
  collect()
  
# Interesting... there are some capture surveys which are not labeled as captures... I wonder if there are any others for other projects.
data_capture_misname = db_capture %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(detection_type,
         detection_subtype,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    detection_type != "capture",
    ) %>%
  distinct() %>%
  collect()

data_ves_misname = db_ves %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(ves_id,
         taxon_ves,
         detection_type,
         detection_subtype,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    detection_type != "visual",
    ) %>%
  collect()

data_aural_misname = db_aural %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(aural_id,
         taxon_aural,
         detection_type,
         detection_subtype,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    detection_type != "aural",
    ) %>%
  collect()

data_env_misname = db_env %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by =  "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  select(environmental_id,
         detection_type,
         detection_subtype,
         date,
         time_of_day,
         visit_lab,
         project_id,
         site,
         region,
         country) %>%
  filter(
    # visit_lab == "km_pep",
    detection_type != "environmental",
    ) %>%
  collect()

# nope, looks like just from Kira's project. Interesting. I expect this was my doing, I'll fix it. Thanks Kira for helping identify this.
```

# how far back does environmental data go?
```{r}
q_env = db_env %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  group_by(country, region) %>%
  summarise(total_env_surveys = n(),
            first_year = min(year(date)),
            env_survey_years = n_distinct(year(date)),
            .groups = "drop") %>%
  collect()

write_csv(q_env, here("staging", "env_survey_summary_2025-09-11.csv"))

q_env_pa = db_env %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(country == "panama",
         date >= "2012-01-01") %>%
  arrange(date) %>%
  collect()

keep_cols = q_env_pa %>%
  keep(~!all(is.na(.x))) %>%
  names()

q_env_pa_clean = q_env_pa %>%
  select(all_of(keep_cols))

```

# penn 2022-05-18 captures and samples
```{r}
q_20220518 = db_sample %>%
  full_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  filter(region == "pennsylvania",
         date == "2022-05-18") %>%
  arrange(taxon_capture,
          time_of_capture) %>%
  collect()
```

# penn 2022 captures and samples
```{r}
q_2022 = db_sample %>%
  full_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  filter(region == "pennsylvania",
         year(date) == 2022) %>%
  select(sample_id,
         sample_name,
         capture_id,
         sample_type,
         taxon_capture,
         time_of_capture,
         date,
         site) %>%
  arrange(date,
          site,
          time_of_capture,
          capture_id,
          sample_type) %>%
  collect()
```

# investigate daytime Penn visits
```{r}
penn_day = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  filter(region == "pennsylvania",
         time_of_day == "day") %>%
  collect() %>%
  arrange(date, site, start_time)

```

# shiny ves query test
```{r}
g_data_ves = db_ves %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  mutate(year = year(date)) %>% 
  select(!c(country_id, region_id, site_id, visit_id, survey_id, ves_id)) %>%
  group_by(country, year) %>%
  summarize(n_ves = sum(count_ves),
            n_days = n_distinct(date),
            .groups = "drop") %>%
  collect()


g_data_capture = db_capture %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  mutate(year = year(date)) %>% 
  select(!c(country_id, region_id, site_id, visit_id, survey_id, capture_id)) %>%
  group_by(country, year) %>%
  summarize(n_capture = n(),
            n_days = n_distinct(date),
            .groups = "drop") %>%
  collect()

g_data_edna = db_edna %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  mutate(year = year(date)) %>% 
  select(!c(country_id, region_id, site_id, visit_id, survey_id, edna_id)) %>%
  collect()

g_edna_years <- g_data_edna %>% 
  select(year) %>%
  distinct(year) %>%
  collect() %>%
  arrange(year) %>%
  drop_na()

```

# Caecilia
```{r}

caecilia = db_capture %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(taxon_capture == "gymnophiona") %>%
  collect()

```

# SN edna
```{r}

sn_edna = db_edna %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(region == "california") %>%
  collect()
```

# all AMP sites
```{r}
bd_sites = db_bd %>%
  inner_join(db_sample, by = "sample_id") %>%
  inner_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "bd") %>%
  group_by(site, region, country) %>%
  summarize(first_swab = min(date),
            last_swab = max(date),
            .groups = "drop") %>%
  collect() %>%
  arrange(site)

amp_sites = db_sample %>%
  inner_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "amp") %>%
  select(site, region, country) %>%
  distinct() %>%
  collect() %>%
  arrange(site)

microbiome_sites = db_sample %>%
  inner_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "microbiome") %>%
  select(site, region, country) %>%
  distinct() %>%
  collect() %>%
  arrange(site)

mucosome_sites = db_sample %>%
  inner_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "mucosome") %>%
  select(site, region, country) %>%
  distinct() %>%
  collect() %>%
  arrange(site)
```