---
title: "bd_qpcr_plate_qc_table_build"
format: html
---

## Setup

```{r}
librarian::shelf(tidyverse, dbplyr, here, janitor, lubridate, rio, RPostgres, stringr, DBI, parsedate, uuid, hms, RIBBiTR-BII/ribbitrrr)
# librarian::shelf(RIBBiTR-BII/ribbitrrr, update_all = TRUE)

## Connect to DB
dbcon <- hopToDB("wibbitr")

```

## load table pointers

```{r}
mdc = tbl(dbcon, Id("survey_data", "metadata_columns")) %>%
  collect()

db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))

```

# extract plate info

```{r}
results_cols = c("result_id",
                 "sample_id",
                 "sample_name_bd",
                 "detected",
                 "replicate",  # singlet, etc.
                 "replicate_count",  # "replicate number (1 - n)
                 "replicate_detected",  # drop
                 "cycle_quant",
                 "target_quant",
                 "qpcr_dilution_factor",
                 "swab_type",
                 "target_quant_per_swab",
                 "its1_copies_per_target_unit",
                 "its1_copies_per_swab",
                 "qpcr_well",
                 "comments_qpcr",
                 "qpcr_plate_id",
                 "extraction_plate_id")

# see SN qpcr for example
qc_cols = c()

qpcr_plate_cols = c("qpcr_plate_id",
                    "total_qpcr_volume_uL",
                    "template_dna_volume_uL",
                    "extract_volume_uL",
                    "standard_target_type",
                    "standard",
                    "master_mix",
                    "qpcr_plate_name",
                    "qpcr_plate_run",
                    "qpcr_date",
                    "qpcr_machine",
                    "qpcr_lab")

extraction_plate_cols = c("extraction_plate_id",
                          "extraction_plate_name",
                          "extraction_date",
                          "extraction_kit",
                          "extraction_lab")


qpcr_plate = db_bd %>%
  select(any_of(qpcr_plate_cols)) %>%
  distinct() %>%
  collect()

extraction_plate = db_bd %>%
  select(any_of(extraction_plate_cols)) %>%
  distinct() %>%
  collect()

qpcr_plate_dupes = get_dupes(qpcr_plate, qpcr_plate_name)
extraction_plate_dupes = get_dupes(extraction_plate, extraction_plate_name)

plates = data_plate %>%
  group_by(qpcr_plate_name) %>%
  count()

# is extraction plate 1:1 with qpcr plate? if not, leave in results... or seperate table...?

# drop all controls
# write controls into push scripts

# drop plate_cols from results table

```