---
title: "bd_qpcr_calculated_columns"
format: html
---

## Setup

```{r}
librarian::shelf(tidyverse, dbplyr, here, janitor, lubridate, rio, RPostgres, stringr, DBI, parsedate, uuid, hms, RIBBiTR-BII/ribbitrrr)
# librarian::shelf(RIBBiTR-BII/ribbitrrr, update_all = TRUE)

## Connect to DB
dbcon <- hopToDB("wibbitr")

```

## load table pointers

```{r}
mdc = tbl(dbcon, Id("survey_data", "metadata_columns")) %>%
  collect()

db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))

```

# see where dependent columns are missing
```{r}
report = db_bd %>%
  collect() %>%
  summarise(count = n(),
            na_dilution = sum(is.na(qpcr_dilution_factor)),
            na_extract = sum(is.na(extract_volume_uL)),
            na_template = sum(is.na(template_dna_volume_uL)),
            na_type = sum(is.na(standard_target_type)),
            na_standard = sum(is.na(standard)))

peace = db_bd %>%
  filter(is.na(standard)) %>%
  collect() %>%
  arrange(sample_name_bd)


```

# calculations

```{r}
bd_calc = db_bd %>%
  mutate(target_quant_per_swab = target_quant * qpcr_dilution_factor * extract_volume_uL / template_dna_volume_uL,
         its1_copies_per_standard_unit = case_match(standard_target_type,
                                                    "ITS1" ~ 1,
                                                    "zoospore" ~ 60,
                                                    .default = NA),
         bd_its1_copies_per_swab = target_quant_per_swab * its1_copies_per_standard_unit)

db_bd = db_bd %>%
  rows_update(bd_calc, by = "result_id", in_place = TRUE, unmatched = "ignore")

# add definitions to metadata
```