---
title: "bd qPCR push Richards-Zawacki"
format: html
editor: source
---

## Setup

```{r}
librarian::shelf(tidyverse, dbplyr, here, janitor, lubridate, rio, RPostgres, stringr, DBI, parsedate, uuid, hms, RIBBiTR-BII/ribbitrrr)
# librarian::shelf(RIBBiTR-BII/ribbitrrr, update_all = TRUE)

## Connect to DB
dbcon = hopToDB("wibbitr")

## Point to local data directory
ddir = Sys.getenv("data_dir")  # data directory
# Keeping .csv files in a central directory. Naming convention uses download date to distinguish batches.
wddir = here(ddir, "bd_qpcr_results", "ribbitr_data_2026-02-03", "ribbitr_data") # working data directory

## load table pointers
mdc = tbl(dbcon, Id("survey_data", "metadata_columns")) %>%
  collect()

db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
db_sample = tbl(dbcon, Id("survey_data", "sample"))

```

## load results from file

```{r}
#| include: false
list.files(here(wddir, "Brazil2024/Individual_Plate_results"))

# brasil
## 2022
raw_br_2022_01 = import_list(here(wddir, "Brazil2022", "RIBBiTR_BrazilSwabs2022_10132023_Plate1_RERUN2_RESULTS.xlsx"))
raw_br_2022_03 = import_list(here(wddir, "Brazil2022", "RIBBiTR_BrazilSwabs2022_08172023_Plate3_RERUN_Results.xlsx"))
raw_br_2022_04 = import_list(here(wddir, "Brazil2022", "RIBBiTR_BrazilSwabs2022_10132023_Plate4_RESULTS.xlsx"))
## 2023
raw_br_2023_01 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03252024_plate1_RERUN_results.xlsx"))
raw_br_2023_02 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03082024_plate2_Results.xlsx"))
raw_br_2023_03 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03112024_plate3_Results.xlsx"))
raw_br_2023_04 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03142024_plate4_Results.xlsx"))
raw_br_2023_05 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03142024_plate5_Results.xlsx"))
raw_br_2023_06 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_03262024_plate6_Results.xlsx"))
raw_br_2023_07 = import_list(here(wddir, "Brazil2023", "RIBBiTR_BrazilSwabs2023_04122024_plate7_results.xlsx"))
## 2024
# raw_br_2024_01 = import_list(here(wddir, "Brazil2024", "RIBBiTR_BrazilSwabs2024_CompiledResults_01132026.xlsx"))[["Results"]]
raw_br_2024_01 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_08132025_plate1_results.xlsx"))
raw_br_2024_02 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_08212025_plate2_results.xlsx"))
raw_br_2024_03 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_09032025_plate3_results.xlsx"))
raw_br_2024_04 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_09192025_plate4_results.xlsx"))
raw_br_2024_05 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_09222025_plate5_results.xlsx"))
raw_br_2024_06 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_09222025_plate6_results.xlsx"))
raw_br_2024_07 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_12032025_plate7_rerun_results.xlsx"))
raw_br_2024_08 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_11252025_plate8_results.xlsx"))
raw_br_2024_10 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_01072026_plate10_results.xlsx"))
raw_br_2024_11 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_01082026_plate11_results.xlsx"))
raw_br_2024_12 = import_list(here(wddir, "Brazil2024", "Individual_Plate_results", "RIBBiTR_BrazilSwabs2024_01122026_SingleTube_results.xlsx"))

# panama
## 2022
raw_pa_2022_01 = import_list(here(wddir, "Panama2022", "RIBBiTR_PanamaSwabs2022_10022023_Plate1_Results.xlsx"))
raw_pa_2022_02 = import_list(here(wddir, "Panama2022", "RIBBiTR_PanamaSwabs2022_10232023_Plate2_Results.xlsx"))
raw_pa_2022_03 = import_list(here(wddir, "Panama2022", "RIBBiTR_PanamaSwabs2022_11062023_Plate3_Results.xlsx"))
raw_pa_2022_04 = import_list(here(wddir, "Panama2022", "RIBBiTR_PanamaSwabs2022_01082024_Plate4_RERUN2_Results.xlsx"))
raw_pa_2022_05 = import_list(here(wddir, "Panama2022", "RIBBiTR_PanamaSwabs2022_01112024_Plate5_Results.xlsx"))
## 2023
raw_pa_2023_01 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_05022024_plate1_results.xlsx"))
raw_pa_2023_02 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_05022024_plate2_results.xlsx"))
raw_pa_2023_03 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_05062024_plate3_results.xlsx"))
raw_pa_2023_04 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_05092024_plate4_results.xlsx"))
raw_pa_2023_05 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_05312024_plate5_results.xlsx"))
raw_pa_2023_06 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07032024_plate6_results.xlsx"))
raw_pa_2023_07 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_06112024_plate7_results.xlsx"))
raw_pa_2023_08 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07032024_plate8_results.xlsx"))
raw_pa_2023_09 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07082024_plate9_results.xlsx"))
raw_pa_2023_10 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07092024_plate10_results.xlsx"))
raw_pa_2023_11 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07122024_plate11_results.xlsx"))
raw_pa_2023_12 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07122024_plate12_results.xlsx"))
raw_pa_2023_13 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07252024_plate13_results.xlsx"))
raw_pa_2023_14 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_07262024_plate14_results.xlsx"))
raw_pa_2023_15 = import_list(here(wddir, "Panama2023", "RIBBiTR_PanamaSwabs2023_08062024_plate15_results.xlsx"))
## 2023NovDec
raw_pa_2023nd_01 = import_list(here(wddir, "PanamaNovDec2023", "RIBBiTR_PanamaSwabsNovDec2023_11192024_Plate1_results.xlsx"))
raw_pa_2023nd_02 = import_list(here(wddir, "PanamaNovDec2023", "RIBBiTR_PanamaSwabsNovDec2023_12112024_Plate2_results.xlsx"))
raw_pa_2023nd_03 = import_list(here(wddir, "PanamaNovDec2023", "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3_results.xlsx"))
## 2024
raw_pa_2024_01 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_05212025_Plate1_results.xlsx"))
raw_pa_2024_02 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_06122025_Plate2_results.xlsx"))
raw_pa_2024_03 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_06132025_Plate3_results.xlsx"))
raw_pa_2024_04 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_06162025_Plate4_results.xlsx"))
raw_pa_2024_05 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_06172025_Plate5_results.xlsx"))
raw_pa_2024_06 = import_list(here(wddir, "Panama2024", "RIBBiTR_PanamaSwabs2024_06172025_Plate6_results.xlsx"))


# penn
## 2022
raw_pe_2022_01 = import_list(here(wddir, "Penn2022", "PaBdSwabs2022_plate1RERUN_03212023_results!.xlsx"))
raw_pe_2022_02 = import_list(here(wddir, "Penn2022", "PaBdSwabs2022_04062023_Plate2_Results!.xlsx"))
# raw_pe_hmm = import_list(here(wddir, "Penn2022", "PaBdSwabs2022_qPCR_03022023_Plate 1_RBV_RESULTS.xls"))
## 2023
raw_pe_2023_01 = import_list(here(wddir, "Penn2023", "RIBBiTR_qPCR_Penn2023_17August2023_Plate1_RESULTS.xls"))
raw_pe_2023_02 = import_list(here(wddir, "Penn2023", "RIBBiTR_qPCR_Penn2023_17August2023_Plate2_RESULTS.xls"))
raw_pe_2023_03 = import_list(here(wddir, "Penn2023", "RIBBiTR_qPCR_Penn2023_18August2023_Plate3_Results.xlsx"))
## 2024
raw_pe_2024_01 = import_list(here(wddir, "Penn2024", "RIBBiTR_PennSwabs2024_02032025_Plate1_Results.xlsx"))
raw_pe_2024_02 = import_list(here(wddir, "Penn2024", "RIBBiTR_PennSwabs2024_02052025_Plate2_Results.xlsx"))
raw_pe_2024_03 = import_list(here(wddir, "Penn2024", "RIBBiTR_PennSwabs2024_02102025_Plate3_Results.xlsx"))
raw_pe_2024_04 = import_list(here(wddir, "Penn2024", "RIBBiTR_PennSwabs2024_02112025_Plate4_Results.xlsx"))
raw_pe_2024_05 = import_list(here(wddir, "Penn2024", "RIBBiTR_PennSwabs2024_02272025_Plate5_Rerun_results.xlsx"))
## 2025
raw_pe_2025_01 = import_list(here(wddir, "Penn2025", "RIBBiTR_PennSwabs2025_11032025_Plate1_rerun2_results.xlsx"))
raw_pe_2025_02 = import_list(here(wddir, "Penn2025", "RIBBiTR_PennSwabs2025_11112025_Plate2_results.xlsx"))
raw_pe_2025_03 = import_list(here(wddir, "Penn2025", "RIBBiTR_PennSwabs2025_11132025_Plate3_results.xlsx"))
raw_pe_2025_04 = import_list(here(wddir, "Penn2025", "RIBBiTR_PennSwabs2025_11252025_Plate4_results.xlsx"))

tz_local = "America/New_York"

```

## scrape xls files & clean data
```{r}
scrape_qpcr_xls <- function(raw_xls) {
  xls <- clean_names(raw_xls)
  
  experiment_name <- str_replace(first(xls$sample_setup[which(xls$sample_setup[,1] == "Experiment Name"),2]), ".edt", "")
  chemistry <- tolower(first(xls$sample_setup[which(xls$sample_setup[,1] == "Chemistry"),2]))
  
  clean_xls <- xls$working_results %>%
    clean_names() %>%
    mutate(
      qpcr_plate_name = ifelse("q_pcr_plate" %in% names(.), q_pcr_plate, experiment_name),
      extraction_plate_name = ifelse("extraction_plate" %in% names(.), extraction_plate, NA_character_),
      qpcr_plate_run = case_when(
        !str_detect(qpcr_plate_name, "RERUN") ~ 1L,
        str_detect(qpcr_plate_name, "RERUN(?!\\d)") ~ 2L,
        TRUE ~ as.integer(str_extract(qpcr_plate_name, "RERUN(\\d+)") %>% str_replace("RERUN", "")) + 1L),
      qpcr_date = as.Date(parse_date_time(str_extract(qpcr_plate_name, "\\d{8}"), orders = "mdY")),
      extraction_date = as.Date(parse_date_time(str_extract(extraction_plate_name, "\\d{8}"), orders = "mdY")),
      master_mix = chemistry
    )
  
  namelist = c("sample_name",
               "bd_ct_mean",
               "bd_quantity_mean",
               "extraction_plate",
               "q_pcr_plate",
               "qpcr_date",
               "extraction_date",
               "master_mix",
               "plate_run")
  
  cols_not_found = setdiff(namelist, names(clean_xls))
  
  # if (length(cols_not_found) != 0) {
  #   stop(paste0("Required columns not found:", str(cols_not_found)))
  # }
  
  return(clean_xls)
}

extract_results = function(raw_xls) {
  xls = clean_names(raw_xls)
  results_xls = xls$results %>%
    slice(-(1:41)) %>%  # Drops first n rows
    mutate(across(everything(), ~ .)) %>%  # Optional: ensure types
    {colnames(.) <- .[1, ]; slice(., -1)} %>%
    clean_names()
}


clean_br_2022_01 = scrape_qpcr_xls(raw_br_2022_01) %>%
  mutate(bsal = case_when(
    bsal_quantity_mean == 0 ~ "Negative",
    bsal_quantity_mean > 0 ~ "Positive",
    .default = NA
  ))
clean_br_2022_03 = scrape_qpcr_xls(raw_br_2022_03) %>%
  mutate(bsal = case_when(
    bsal_quantity_mean == 0 ~ "Negative",
    bsal_quantity_mean > 0 ~ "Positive",
    .default = NA
  ))
clean_br_2022_04 = scrape_qpcr_xls(raw_br_2022_04) %>%
  mutate(bsal = case_when(
    bsal_quantity_mean == 0 ~ "Negative",
    bsal_quantity_mean > 0 ~ "Positive",
    .default = NA
  ))

clean_br_2023_01 = scrape_qpcr_xls(raw_br_2023_01) %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_br_2023_02 = scrape_qpcr_xls(raw_br_2023_02)
clean_br_2023_03 = scrape_qpcr_xls(raw_br_2023_03) %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_br_2023_04 = scrape_qpcr_xls(raw_br_2023_04) %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_br_2023_05 = scrape_qpcr_xls(raw_br_2023_05) %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_br_2023_06 = scrape_qpcr_xls(raw_br_2023_06) %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_br_2023_07 = scrape_qpcr_xls(raw_br_2023_07)

# rename BR PCE samples with "pce_" prefix
clean_br_2023_all = bind_rows(clean_br_2023_01,
                              clean_br_2023_02,
                              clean_br_2023_03,
                              clean_br_2023_04,
                              clean_br_2023_05,
                              clean_br_2023_06,
                              clean_br_2023_07) %>%
  mutate(sample_name_drop = sample_name,
         sample_name = ifelse(grepl("^[0-9]{3}$", sample_name),
                              paste0("BRBD ", sample_name),
                              sample_name))

clean_br_2024_01 = scrape_qpcr_xls(raw_br_2024_01)
clean_br_2024_02 = scrape_qpcr_xls(raw_br_2024_02)
clean_br_2024_03 = scrape_qpcr_xls(raw_br_2024_03)
clean_br_2024_04 = scrape_qpcr_xls(raw_br_2024_04)
clean_br_2024_05 = scrape_qpcr_xls(raw_br_2024_05)
clean_br_2024_06 = scrape_qpcr_xls(raw_br_2024_06) %>%
  rename(q_pcr_well = well,
         q_pcr_well_position = well_position)
clean_br_2024_07 = scrape_qpcr_xls(raw_br_2024_07)
clean_br_2024_08 = scrape_qpcr_xls(raw_br_2024_08)
clean_br_2024_10 = scrape_qpcr_xls(raw_br_2024_10)
clean_br_2024_11 = scrape_qpcr_xls(raw_br_2024_11)
clean_br_2024_12 = scrape_qpcr_xls(raw_br_2024_12)

clean_br_2024_all = bind_rows(clean_br_2024_01,
                              clean_br_2024_02,
                              clean_br_2024_03,
                              clean_br_2024_04,
                              clean_br_2024_05,
                              clean_br_2024_06,
                              clean_br_2024_07,
                              clean_br_2024_08,
                              clean_br_2024_10,
                              clean_br_2024_11,
                              clean_br_2024_12)

clean_pa_2022_01 = scrape_qpcr_xls(raw_pa_2022_01) %>%
  rename(bsal = bsal_pos_neg)
clean_pa_2022_02 = scrape_qpcr_xls(raw_pa_2022_02) %>%
  rename(bsal = bsal_pos_neg)
clean_pa_2022_03 = scrape_qpcr_xls(raw_pa_2022_03) %>%
  rename(bsal = bsal_pos_neg)
clean_pa_2022_04 = scrape_qpcr_xls(raw_pa_2022_04) %>%
  rename(bsal = bsal_pos_neg)
clean_pa_2022_05 = scrape_qpcr_xls(raw_pa_2022_05) %>%
  rename(bsal = bsal_pos_neg)

clean_pa_2023_01 = scrape_qpcr_xls(raw_pa_2023_01)
clean_pa_2023_02 = scrape_qpcr_xls(raw_pa_2023_02)
clean_pa_2023_03 = scrape_qpcr_xls(raw_pa_2023_03)
clean_pa_2023_04 = scrape_qpcr_xls(raw_pa_2023_04)
clean_pa_2023_05 = scrape_qpcr_xls(raw_pa_2023_05)
clean_pa_2023_06 = scrape_qpcr_xls(raw_pa_2023_06)
clean_pa_2023_07 = scrape_qpcr_xls(raw_pa_2023_07)
clean_pa_2023_08 = scrape_qpcr_xls(raw_pa_2023_08) %>%
  mutate(sample_name = str_replace_all(sample_name, "_(\\w{0,2})(?=\\d)", ~ toupper(.x)))
clean_pa_2023_09 = scrape_qpcr_xls(raw_pa_2023_09)
clean_pa_2023_10 = scrape_qpcr_xls(raw_pa_2023_10)
clean_pa_2023_11 = scrape_qpcr_xls(raw_pa_2023_11)
clean_pa_2023_12 = scrape_qpcr_xls(raw_pa_2023_12)
clean_pa_2023_13 = scrape_qpcr_xls(raw_pa_2023_13)
clean_pa_2023_14 = scrape_qpcr_xls(raw_pa_2023_14)
clean_pa_2023_15 = scrape_qpcr_xls(raw_pa_2023_15)

clean_pa_2023nd_01 = scrape_qpcr_xls(raw_pa_2023nd_01)
clean_pa_2023nd_02 = scrape_qpcr_xls(raw_pa_2023nd_02)
clean_pa_2023nd_03 = scrape_qpcr_xls(raw_pa_2023nd_03)

clean_pa_2024_01 = scrape_qpcr_xls(raw_pa_2024_01)
clean_pa_2024_02 = scrape_qpcr_xls(raw_pa_2024_02)
clean_pa_2024_03 = scrape_qpcr_xls(raw_pa_2024_03)
clean_pa_2024_04 = scrape_qpcr_xls(raw_pa_2024_04)
clean_pa_2024_05 = scrape_qpcr_xls(raw_pa_2024_05)
clean_pa_2024_06 = scrape_qpcr_xls(raw_pa_2024_06)

clean_pe_2022_01 = scrape_qpcr_xls(raw_pe_2022_01) %>%
  left_join(extract_results(raw_pe_2022_01) %>%
              filter(target_name == "IPC") %>%
              mutate(ipc = case_when(
                ct == "Undetermined" ~ "Fail",
                .default = "Pass")) %>%
              select(sample_name,
                     ipc), by = "sample_name") %>%
  left_join(extract_results(raw_pe_2022_01) %>%
              filter(target_name == "Bsal") %>%
              mutate(bsal = case_when(
                ct == "Undetermined" ~ "Negative",
                .default = "Positive")) %>%
              select(sample_name,
                     bsal), by = "sample_name") %>%
  mutate(sample_name = gsub("DRY0", "DrySwab0", sample_name),
         bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         )) %>%
  filter(!is.na(well))
  

clean_pe_2022_02 = scrape_qpcr_xls(raw_pe_2022_02) %>%
  left_join(extract_results(raw_pe_2022_02) %>%
              filter(target_name == "IPC") %>%
              mutate(ipc = case_when(
                ct == "Undetermined" ~ "Fail",
                .default = "Pass")) %>%
              select(sample_name,
                     ipc), by = "sample_name") %>%
  left_join(extract_results(raw_pe_2022_02) %>%
              filter(target_name == "Bsal") %>%
              mutate(bsal = case_when(
                ct == "Undetermined" ~ "Negative",
                .default = "Positive")) %>%
              select(sample_name,
                     bsal), by = "sample_name") %>%
  mutate(bd_quantity_mean = as.numeric(bd_quantity_mean),
         sample_name = gsub("BDSwab", "BdSwab", sample_name))

clean_pe_2023_01 = scrape_qpcr_xls(raw_pe_2023_01) %>%
  rename(bd_ct_mean = ct_mean,
         bd_quantity_mean = quantity_mean)  %>%
  mutate(bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ),
         ipc = if_else(is.na(ipc), "Pass", ipc),
         bsal = if_else(is.na(bsal_ct), "Negative", "Positive"))

clean_pe_2023_02 = scrape_qpcr_xls(raw_pe_2023_02) %>%
  left_join(extract_results(raw_pe_2023_02) %>%
              filter(target_name == "IPC") %>%
              mutate(ipc = case_when(
                ct == "Undetermined" ~ "Fail",
                .default = "Pass")) %>%
              select(sample_name,
                     ipc), by = "sample_name") %>%
  left_join(extract_results(raw_pe_2023_02) %>%
              filter(target_name == "Bsal") %>%
              mutate(bsal = case_when(
                ct == "Undetermined" ~ "Negative",
                .default = "Positive")) %>%
              select(sample_name,
                     bsal), by = "sample_name") %>%
  rename(bd_ct_mean = ct_mean,
         bd_quantity_mean = quantity_mean) %>%
  mutate(bd_quantity_mean = as.numeric(bd_quantity_mean),
         bd_pos_neg = case_when(
           bd_ct_mean > 0 ~ "Positive",
           is.na(bd_ct_mean) ~ "Negative",
           .default = NA
         ))
clean_pe_2023_03 = scrape_qpcr_xls(raw_pe_2023_03) %>%
  mutate(qpcr_date = as.Date("2023-08-18"))

clean_pe_2023_all = bind_rows(clean_pe_2023_01,
                              clean_pe_2023_02,
                              clean_pe_2023_03) %>%
  mutate(sample_name_drop = sample_name,
         sample_name = sub(" well [A-Z]\\d{1,2}$", "", sample_name),
         sample_name = sub("^(Pe_Bd)0(\\d{5})$", "\\1\\2", sample_name))


pp = grepl(" well [A-Z]\\d{1,2}$", clean_pe_2023_all$sample_name_new) # check for well format

clean_pe_2024_01 = scrape_qpcr_xls(raw_pe_2024_01)
clean_pe_2024_02 = scrape_qpcr_xls(raw_pe_2024_02)
clean_pe_2024_03 = scrape_qpcr_xls(raw_pe_2024_03)
clean_pe_2024_04 = scrape_qpcr_xls(raw_pe_2024_04)
clean_pe_2024_05 = scrape_qpcr_xls(raw_pe_2024_05)

clean_pe_2025_01 = scrape_qpcr_xls(raw_pe_2025_01)
clean_pe_2025_02 = scrape_qpcr_xls(raw_pe_2025_02)
clean_pe_2025_03 = scrape_qpcr_xls(raw_pe_2025_03)
clean_pe_2025_04 = scrape_qpcr_xls(raw_pe_2025_04)

# clean up sample names with forbidden characters
clean_pe_2022_02$bd_quantity_mean[clean_pe_2022_02$sample_name == "2022-05-18-admin-rapi18"] = 11603.6640625
clean_pe_2022_02$bd_quantity_mean[clean_pe_2022_02$sample_name == "2022-05-18‐admin-rapi16"] = 11241.6748046875
clean_pe_2022_02$sample_name[clean_pe_2022_02$sample_name == "2022-05-18‐admin-rapi16"] = "2022-05-18-admin-rapi16"
clean_pe_2022_02$bd_quantity_mean[clean_pe_2022_02$sample_name == "POS 3.27.23"] = 1101634

#bind to one dataframe
bind_results = bind_rows(clean_br_2022_01,
                         clean_br_2022_03,
                         clean_br_2022_04,
                         clean_br_2023_all,
                         clean_br_2024_all,
                         clean_pa_2022_02,
                         clean_pa_2022_03,
                         clean_pa_2022_04,
                         clean_pa_2022_05,
                         clean_pa_2023_01,
                         clean_pa_2023_02,
                         clean_pa_2023_03,
                         clean_pa_2023_04,
                         clean_pa_2023_05,
                         clean_pa_2023_06,
                         clean_pa_2023_07,
                         clean_pa_2023_08,
                         clean_pa_2023_09,
                         clean_pa_2023_10,
                         clean_pa_2023_11,
                         clean_pa_2023_12,
                         clean_pa_2023_13,
                         clean_pa_2023_14,
                         clean_pa_2023_15,
                         clean_pa_2023nd_01,
                         clean_pa_2023nd_02,
                         clean_pa_2023nd_03,
                         clean_pa_2024_01,
                         clean_pa_2024_02,
                         clean_pa_2024_03,
                         clean_pa_2024_04,
                         clean_pa_2024_05,
                         clean_pa_2024_06,
                         clean_pe_2022_01,
                         clean_pe_2022_02,
                         clean_pe_2023_all,
                         clean_pe_2024_01,
                         clean_pe_2024_02,
                         clean_pe_2024_03,
                         clean_pe_2024_04,
                         clean_pe_2024_05,
                         clean_pe_2025_01,
                         clean_pe_2025_02,
                         clean_pe_2025_03,
                         clean_pe_2025_04)

clean_results = bind_results %>%
  rename(bd_cycle_quant = bd_ct_mean,
         bd_target_quant = bd_quantity_mean,
         sample_control = sample_type,
         qpcr_well = well,
         comments_qpcr = comments) %>%
  mutate(sample_type = "bd",
         bd_detected = case_when(bd_pos_neg %in% c("Positive", "pos") ~ 1,
                                 bd_target_quant > 0 ~ 1,
                                 bd_pos_neg %in% c("Negative", "neg") ~ 0,
                                 bd_target_quant == 0 ~ 0,
                                 TRUE ~ NA_real_),
         bd_target_quant = ifelse(is.na(bd_target_quant) & bd_detected == 0,
                               0,
                               bd_target_quant),
         qpcr_well = as.character(qpcr_well),
         qpcr_lab = "rz_lab",
         replicate_id = 1,
         replicates = "singlet",
         extraction_lab = "rz_lab",
         extraction_kit = "qiagen_dneasy",
         standard = "plasmid-pisces",
         standard_target_type = "ITS1",
         qpcr_machine = "quantstudio_3",
         swab_type = "mw113",
         qpcr_dilution_factor = 1,
         template_dna_volume_uL = 5,
         extract_volume_uL = 20,
         total_qpcr_volume_uL = 25,
         sample_control = ifelse(sample_name %in% c("qPCR Negative", "Negative Swab", "Positive Swab", "POS EXTRACT CONTROL", "NEG EXTRACT CONTROL"), "Control", sample_control),
         bd_target_quant_per_swab = bd_target_quant * qpcr_dilution_factor * extract_volume_uL / template_dna_volume_uL,
         its1_copies_per_standard_unit = recode_values(standard_target_type,
                                                       "ITS1" ~ 1,
                                                       "zoospore" ~ 60,
                                                       default = NA),
         bd_its1_copies_per_swab = bd_target_quant_per_swab * its1_copies_per_standard_unit,
         ipc = tolower(ipc),
         bsal_detected = recode_values(tolower(bsal),
                                       "positive" ~ TRUE,
                                       "negative" ~ FALSE,
                                       default = NA)) %>%
  filter(!is.na(sample_name),
         sample_control != "Control" | is.na(sample_control),
         !str_detect(sample_name, "^Pisces"),
         target_name == "Bd" | is.na(target_name),
         is.na(ipc) | ipc == "pass") %>%
  arrange(sample_name, desc(rerun)) %>%
  group_by(sample_name) %>%
  filter(
    # Check if both "Y" and "N" exist in the group
    if (all(c("Y", "N") %in% rerun)) {
      rerun == "Y"  # Keep only rerun == "Y"
    } else {
      TRUE          # Otherwise, keep all rows
    }
  ) %>%
  ungroup()

```

# checks
```{r}
qc_results_a = clean_results %>%
  mutate(
    sample_name = case_when(
      sample_name == "221120_J001" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabs2022_11062023_Plate3" & 
        qpcr_well == "18" ~ "221120_J001_a",
      sample_name == "221120_J001" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabs2023_07032024_plate8" & 
        qpcr_well == "61" ~ "221120_J001_b",
      sample_name == "221121_J011" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabs2023_07032024_plate8" & 
        qpcr_well == "50" ~ "221121_J010",
      sample_name == "230719_F021" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabs2023_07082024_plate9" & 
        qpcr_well == "27" ~ "230719_F021_b",
      sample_name == "231201_S001" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "73" ~ "231202_S001",
      sample_name == "231201_S002" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "85" ~ "231202_S002",
      sample_name == "231201_S003" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "2" ~ "231202_S003",
      sample_name == "231201_S004" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "14" ~ "231202_S004",
      sample_name == "231201_S005" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "26" ~ "231202_S005",
      sample_name == "231201_S006" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "38" ~ "231202_S006",
      sample_name == "231201_S007" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "50" ~ "231202_S007",
      sample_name == "231201_S008" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "62" ~ "231202_S008",
      sample_name == "231201_S009" & 
        qpcr_plate_name == "RIBBiTR_PanamaSwabsNovDec2023_12192024_Plate3" & 
        qpcr_well == "74" ~ "231202_S009",
      TRUE ~ sample_name
    )
  ) %>%
  filter(
    !(sample_name == "221118_019" & 
       qpcr_plate_name == "RIBBiTR_PanamaSwabs2022_10022023_Plate1" & 
       qpcr_well == "91"),
    !(sample_name == "221120_J001" & 
       qpcr_plate_name == "RIBBiTR_PanamaSwabs2023_07032024_plate8" & 
       qpcr_well == "73"),
    !(sample_name == "221212_051" & 
       qpcr_plate_name == "RIBBiTR_PanamaSwabs2022_11062023_Plate3" & 
       qpcr_well == "5")
  )

bd_na = clean_results %>%
  filter(is.na(bd_its1_copies_per_swab) | is.na(bd_detected)) %>%
  select(bd_detected,
         bd_its1_copies_per_swab,
         qpcr_plate_name,
         everything()) %>%
  arrange(qpcr_plate_name)

if(nrow(bd_na) > 0) warning("NA values found in `bd_detected` and/or `bd_its1_copies_per_swab`")

violations_unique = get_dupes(qc_results_a, sample_name)

violations_drop = violations_unique %>%
  group_by(sample_name) %>%
  slice_min(qpcr_date) %>%
  ungroup()

warning(paste0("Dropping ", nrow(violations_drop), " Bd results due to duplicate entries (keeping latest)."))

ipc_fail = qc_results_a %>%
  filter(ipc != "pass")

if (nrow(ipc_fail) > 0) {
  warning("Some samples have IPC = `fail`")
}

# drop offending duplicates
qc_results = qc_results_a %>%
  anti_join(violations_drop, by = c("sample_name", "qpcr_plate_name", "qpcr_well"))

# write_csv(violations_unique %>%
#             select(sample_name,
#                    bd_pos_neg,
#                    cycle_quant,
#                    target_quant,
#                    extraction_plate_name,
#                    extraction_date,
#                    extraction_well,
#                    qpcr_plate_name,
#                    qpcr_date,
#                    qpcr_well), here("staging", paste0("bd_qpcr_duplicates_", today(), ".csv")))

```

# gelled
```{r}
# align data with ids where already exist, otherwise create new ids
gelled_results = qc_results %>%
  left_join(db_sample %>% collect(), by = c("sample_name", "sample_type")) %>%
  group_by(sample_name, sample_type) %>%
  mutate(uuid_name = paste0(sample_name, sample_type),
         sample_id = ifelse(is.na(sample_id), UUIDfromName("1208e62f-d3a1-462c-984f-0bf1f43f5837", uuid_name), sample_id),
         sample_name_drop = ifelse(sample_name == sample_name_drop, NA_character_, sample_name_drop),
         sample_id_drop = ifelse(is.na(sample_name_drop),
                                 NA_character_,
                                 UUIDfromName("1208e62f-d3a1-462c-984f-0bf1f43f5837", paste0(sample_name_drop, sample_type)))) %>%
  ungroup() %>%
  mutate(sample_name_bd = sample_name) %>%
  left_join(db_bd %>% 
              select(sample_name_bd,
                     qpcr_plate_name,
                     qpcr_well,
                     result_id) %>%
              collect(), by = c("sample_name_bd",
                                "qpcr_plate_name",
                                "qpcr_well")) %>%
  group_by(sample_name_bd,
           qpcr_plate_name,
           qpcr_well) %>%
  mutate(uuid_name = paste0(sample_name_bd, qpcr_well, qpcr_plate_name, qpcr_plate_run),
         result_id = ifelse(is.na(result_id), UUIDfromName("d41b1f58-5576-49b6-a303-0bddcc94a0f2", uuid_name), result_id)) %>%
  ungroup()

sample_id_drop = gelled_results %>%
  filter(!is.na(sample_id_drop)) %>%
  select(sample_id_drop, sample_name_drop, sample_name) %>%
  distinct() %>%
  pull(sample_id_drop)
```

# subset data
```{r}
# break wide table into corresponding database tables
subset_bd_samples = gelled_results %>%
  select(any_of(colnames(db_sample))) %>%
  distinct() %>%
  filter(!is.na(sample_id))

compare_bd_samples = compare_df_cols(db_sample %>%
                                  filter(FALSE) %>%
                                  collect(), subset_bd_samples)

# compare sample_id
tray = compare_for_staging(db_sample %>% collect(), subset_bd_samples, "sample_id", return_all = TRUE, report = "sample")
final_bd_samples = bind_rows(tray$insert,
                             tray$update)

# # also compare sample name and type
# tray = compare_for_staging(db_sample %>% collect(), subset_bd_samples, c("sample_name", "sample_type"), return_all = TRUE, report = "sample")
# 
# # also compare sample name conflict and type
# tray = compare_for_staging(db_sample %>% 
#                              mutate(sample_name = sample_name_conflict) %>%
#                              filter(!is.na(sample_name)) %>%
#                              collect(), subset_bd_samples, c("sample_name", "sample_type"), return_all = TRUE, report = "sample")
# 
# peace = db_sample %>%
#   filter(sample_type == "bd",
#          !is.na(sample_name_conflict)) %>%
#   select(sample_name_conflict) %>%
#   distinct() %>%
#   pull(sample_name_conflict)
# 
# news_samps = tray$insert
# 
# poos = subset_bd_samples %>%
#   filter(sample_name %in% peace)

subset_bd = gelled_results %>%
  select(any_of(colnames(db_bd))) %>%
  distinct() %>%
  filter(!is.na(sample_id))

compare_bd = compare_df_cols(db_bd %>%
                               filter(FALSE) %>%
                               collect(), subset_bd)

tray = compare_for_staging(db_bd %>% collect(), subset_bd, "result_id", return_all = TRUE, report = "bd")
final_bd = bind_rows(tray$insert,
                       tray$update)
```

# commit
```{r}

# start transaction
dbBegin(dbcon)

tryCatch(
  {
    # upsert to sample table
    db_sample = db_rows_upsert(dbcon, db_sample, final_bd_samples, by="sample_id")
    # upseret to bd table
    db_bd = db_rows_upsert(dbcon, db_bd, final_bd, by="result_id")
    
    # Commit transaction if successful
    dbCommit(dbcon)
    print("Transaction successful!")
    
  }, error = function(e) {
    # Rollback transaction in case of error
    dbRollback(dbcon)
    message("Transaction failed: ", e$message)
  })

```

```{r}
dbDisconnect(dbcon)
```
