---
title: "site_history_sn"
format: html
---

```{r}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, dbplyr, here, janitor, lubridate, RPostgres, stringr, DBI, uuid, RIBBiTR-BII/ribbitrrr)
# librarian::shelf(RIBBiTR-BII/ribbitrrr, update_all = TRUE)

# connect to database
dbcon = hopToDB("wibbitr")

sncon = hopToDB("amphibians")
```

# pointers
```{r}
db_sh = tbl(dbcon, Id("survey_data", "site_history"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))

sn_relocate = tbl(sncon, Id("relocate"))
sn_relocate_frog = tbl(sncon, Id("relocate_frog"))

```

# import
```{r}

rloc = sn_relocate %>%
  collect()

data_relocate = sn_relocate_frog %>%
  left_join(sn_relocate %>%
              rename(treatment_comment = comment), by = c("relocate_id" = "id")) %>%
  collect()

release_event = data_relocate %>%
  pivot_longer(cols = c("release_siteid1", "release_siteid2"),
               names_to = "site_type",
               values_to = "release_siteid") %>%
  filter(!is.na(release_siteid)) %>%
  group_by(release_siteid, release_date) %>%
  summarize(treatment_size = NA,
            treatment_comment = first(treatment_comment),
            type = first(type)) %>%
  ungroup() %>%
  rename(site = release_siteid,
         treatment_date = release_date) %>%
  mutate(treatment_type = paste0(type, "_release"),
         site = as.character(site),
         treatment_life_stage = "adult") %>%
  filter(!is.na(site))

capture_event = data_relocate %>%
  mutate(collect_siteid = str_split(collect_siteid, ",")) %>%
  unnest(collect_siteid) %>%
  group_by(collect_siteid, collect_date) %>%
  summarize(treatment_count_individuals = NA,
            treatment_comment = first(treatment_comment),
            type = first(type),
            treatment_life_stage = paste0(unique(collect_stage), collapse = ", ")) %>%
  ungroup() %>%
  rename(site = collect_siteid,
         treatment_date = collect_date) %>%
  mutate(treatment_type = paste0(type, "_collection")) %>%
  filter(!is.na(site))

upsert_sh = bind_rows(capture_event,
                       release_event) %>%
  left_join(db_site %>% select(site_id, site) %>% collect(), by = "site") %>%
  mutate(treatment_id = UUIDfromName("50c5404a-3c4b-4352-a7b7-f2ad8b0f7a42", paste(site_id, treatment_date, treatment_type, sep = "_"))) %>%
  select(treatment_id,
         site_id,
         treatment_date,
         treatment_type,
         treatment_size,
         treatment_life_stage,
         treatment_comment) %>%
  filter(!is.na(site_id))

```

# upsert table
```{r}
temp_sh = stage_to_temp(dbcon, db_sh, upsert_sh)
pointer = tbl(dbcon, temp_sh)
db_sh = rows_upsert(db_sh, pointer, by="treatment_id", in_place=TRUE)
```

# antifungal treatments
```{r}
af_treatment_barrett = c(
  "11469",
  "11491",
  "11493"
)

surveys_barrett = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site %in% af_treatment_barrett,
         date >= "2009-07-30",
         date <= "2009-08-05",
         detection_type == "capture") %>%
  collect() %>%
  arrange(date, start_time)

af_treatment_dusy = c(
  "11518",
  "11526",
  "11506",
  "11518"
)

surveys_dusy_1 = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site %in% af_treatment_dusy,
         date >= "2010-07-27",
         date <= "2010-08-02",
         detection_type == "capture") %>%
  collect() %>%
  arrange(date, start_time)

surveys_dusy_2 = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site %in% af_treatment_dusy,
         date >= "2012-07-12",
         date <= "2012-07-18",
         detection_type == "capture") %>%
  collect() %>%
  arrange(date, start_time)

af_treatment_leconte = c(
  "10101",
  "10100"
)

surveys_leconte = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site %in% af_treatment_leconte,
         date >= "2015-08-24",
         date <= "2015-09-15",
         detection_type == "capture") %>%
  collect() %>%
  arrange(date, start_time)

af_treatment_treasure = c(
  "50839"
)

surveys_treasure = db_survey %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  filter(site %in% af_treatment_treasure,
         date >= "2018-07-16",
         date <= "2018-07-23",
         detection_type == "capture") %>%
  collect() %>%
  arrange(date, start_time)

```
